# QuoteGenerator/netlify.toml

[build]
  publish = "."
  command = "echo 'No frontend build command required'"

[functions]
  directory = "netlify/functions"
  # --- IMPORTANT: These lines are crucial for ES Modules ---
  node_bundler = "esbuild"
  # List ALL your npm dependencies that your function uses.
  # This tells Netlify to package them correctly.
  external_node_modules = ["node-fetch", "express", "cors"]
  # --- End of important lines ---

  # Optional: You can explicitly set the Node.js version if you want to.
  # This can also be done via an environment variable in the Netlify UI.
  # node_version = "18" # Or "20"